[build]
  command = "npm run build -- --configuration production && node replace.js"
  publish = "dist/yeh-app/browser"

[context.production.environment]
  ANGULAR_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
